
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sample-model?characterEncoding=utf8?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root
    flyway:
        baseline-on-migrate: true
        enabled: true
    h2:
        console:
            enabled: true
            path: /h2

    jpa:
        hibernate:
            # Hibernate ddl auto (create, create-drop, validate, update) // create-drop works with - import.sql file
            ddl-auto: validate

properties:
    field-injected-property: field property
    constructor-injected-property: constructor property
    property-1: property 1 value
    settings-to-test:
        number: 1
        text: lorem ipsum dolor
        truth: false
        record:
            field1: 1
            field2: 2
            field3: 3